import { createIcon } from "../icons.js";
const modifiedTime = (timestamp) => timestamp == null ? "" : new Date(timestamp * 1000).toLocaleDateString(undefined, { month: "2-digit", day: "2-digit" });

export function createNodeElement(node, handlers) {
  const element=document.createElement("article"); element.className="folder-node"; element.dataset.id=node.panelInstanceId;
  element.innerHTML=`<button class="compact-parent" type="button" hidden><span></span></button><div class="node-title"><strong></strong><button class="node-search" type="button" aria-label="このフォルダー内を検索"></button><button class="node-close" type="button" aria-label="ブランチを閉じる"></button></div><div class="node-contents"><div class="file-region"></div><div class="folder-region"></div></div><div class="node-preview"></div>`;
  element.querySelector(".compact-parent").prepend(createIcon("up"));
  element.querySelector(".node-search").append(createIcon("search")); element.querySelector(".node-close").append(createIcon("close"));
  element.querySelector(".node-close").onclick=e=>{e.stopPropagation();handlers.close(node.panelInstanceId);}; element.querySelector(".node-search").onclick=e=>{e.stopPropagation();handlers.search(node.panelInstanceId);};
  element.querySelector(".compact-parent").onclick=e=>{e.stopPropagation();handlers.parent(node.panelInstanceId);};
  const title=element.querySelector(".node-title"); title.addEventListener("pointerdown",e=>handlers.drag(e,node.panelInstanceId));
  element.addEventListener("contextmenu",e=>{if(e.target.closest(".file-item,.folder-item"))return;e.preventDefault();handlers.selectFolder(node.panelInstanceId);handlers.panelMenu(node.panelInstanceId,e.clientX,e.clientY);});
  return element;
}
function acceptDrop(region,kind,handlers,destinationId,destinationName="",destinationTarget=""){region.dataset.dropKind=kind;region.dataset.destinationId=destinationId;region.dataset.destinationName=destinationName;region.dataset.destinationTarget=destinationTarget;if(region.dataset.dropBound)return;region.dataset.dropBound="true";region.addEventListener("dragover",e=>{if(e.dataTransfer.types.includes(`application/x-nodefilemanager-${region.dataset.dropKind}`)){e.preventDefault();region.classList.add("drop-target");}});region.addEventListener("dragleave",()=>region.classList.remove("drop-target"));region.addEventListener("drop",e=>{e.preventDefault();e.stopPropagation();region.classList.remove("drop-target");handlers.drop(e,region.dataset.destinationId,region.dataset.dropKind);});}
export function updateNodeElement(element,node,selected,selectedItem,openFolders,handlers){
  element.style.transform=`translate(${node.x}px,${node.y}px)`;element.classList.toggle("selected",selected);element.querySelector(".node-title strong").textContent=node.name;
  const compact=element.querySelector(".compact-parent"),parentName=node.compactParent?.name||"";compact.hidden=!node.compactParent;compact.querySelector("span").textContent=parentName;compact.setAttribute("aria-label",`親フォルダーを開く: ${parentName}`);compact.title=parentName;
  const files=element.querySelector(".file-region"),folders=element.querySelector(".folder-region");files.replaceChildren();folders.replaceChildren();
  for(const file of node.files||[]){const row=document.createElement("div");row.className="file-item";row.draggable=true;row.dataset.id=file.id;row.classList.toggle("selected",selectedItem===file.id);row.innerHTML=`<span class="item-icon"></span><span class="item-name"></span><time></time>`;row.querySelector(".item-icon").append(createIcon("file"));row.querySelector(".item-name").textContent=file.name;row.querySelector("time").textContent=modifiedTime(file.modifiedTime);row.onpointerdown=e=>{e.stopPropagation();handlers.selectFile(file,row);};row.onclick=e=>{e.stopPropagation();handlers.preview(node.panelInstanceId,file);};row.ondblclick=e=>{e.stopPropagation();handlers.open(file.id);};row.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();handlers.selectFile(file,row);handlers.rename();};row.ondragstart=e=>{handlers.selectFile(file,row);e.dataTransfer.setData("application/x-nodefilemanager-item",file.id);e.dataTransfer.setData("application/x-nodefilemanager-kind","file");e.dataTransfer.setData("application/x-nodefilemanager-file",file.id);e.dataTransfer.effectAllowed="copyMove";};files.append(row);}
  for(const folder of node.folders||[]){const row=document.createElement("div");row.className="folder-item";row.dataset.id=folder.id;row.classList.toggle("open",openFolders.has(folder.id));row.innerHTML=`<span class="item-icon"></span><span class="item-name"></span>`;row.querySelector(".item-icon").append(createIcon("folder"));row.querySelector(".item-name").textContent=folder.name;row.onpointerdown=e=>e.stopPropagation();row.onclick=e=>{e.stopPropagation();handlers.folder(node.panelInstanceId,folder);};acceptDrop(row,"folder",handlers,folder.id,folder.name,"child-row");folders.append(row);}
  const mixed=files.children.length>0&&folders.children.length>0;element.classList.toggle("mixed-panel",mixed);element.querySelector(".node-contents").classList.toggle("two-column",mixed);files.hidden=!files.children.length;folders.hidden=!folders.children.length;acceptDrop(files,"file",handlers,node.folderId,node.name,"panel-region");acceptDrop(folders,"folder",handlers,node.folderId,node.name,"panel-region");updatePreviewElement(element,node,handlers);
}
export function updatePreviewElement(element,node,handlers){const preview=element.querySelector(".node-preview");preview.replaceChildren();preview.hidden=!node.preview;if(!node.preview)return;const header=document.createElement("div");header.className="preview-title";header.textContent=node.preview.name;const close=document.createElement("button");close.type="button";close.append(createIcon("close"));close.onclick=()=>handlers.closePreview(node.panelInstanceId);header.prepend(close);preview.append(header);const url=`/api/files/preview?id=${encodeURIComponent(node.preview.id)}`;if([".jpg",".jpeg",".png"].includes(node.preview.extension.toLowerCase())){const image=document.createElement("img");image.src=url;image.alt=node.preview.name;image.onload=()=>handlers.previewResized(node.panelInstanceId);preview.append(image);}else{const frame=document.createElement("iframe");frame.src=`${url}#page=${node.preview.page}`;frame.title=node.preview.name;preview.append(frame);}}
